# Generated by Django 6.1 on 2026-09-01 10:06

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, default='General', help_text='e.g. General, Pricing, Process, Design', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='check-circle', help_text='Lucide icon name', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['step_number', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential Construction'), ('commercial', 'Commercial Construction'), ('architectural', 'Architectural Design'), ('structural', 'Structural Solutions'), ('renovation', 'Renovation & Remodeling'), ('landscaping', 'Landscaping & Outdoors'), ('specialized', 'Specialized Solutions')], default='residential', max_length=40)),
                ('location', models.CharField(blank=True, help_text='e.g. Mombasa, Nairobi, Coastal Region', max_length=150)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('scope_of_work', models.TextField(blank=True, help_text='Key highlights or work items undertaken on this project')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=False, help_text='Display on Homepage showcase')),
                ('is_sample', models.BooleanField(default=False, help_text='Label as sample project until actual project photos are uploaded')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('category', models.CharField(choices=[('construction', 'Building & Construction'), ('design', 'Architectural & Engineering'), ('specialized', 'Specialized Building Solutions'), ('renovation', 'Renovation & Maintenance')], default='construction', max_length=30)),
                ('short_description', models.CharField(help_text='Concise summary for cards and search results', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what the service involves, process, and benefits')),
                ('key_features', models.TextField(blank=True, help_text='Comma-separated or bullet points of key highlights and deliverables')),
                ('icon', models.CharField(default='building-2', help_text='Lucide icon name (e.g. building-2, pen-tool, hard-hat, hammer, wrench, compass, trees, droplet)', max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('featured', models.BooleanField(default=False, help_text='Display prominently on homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lowest numbers appear first')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Gen-Z Constructors Limited Company', max_length=200)),
                ('tagline', models.CharField(default='BUILDING YOUR VISION, CONSTRUCTING YOUR FUTURE.', max_length=255)),
                ('phone', models.CharField(default='+254713706103', max_length=50)),
                ('email', models.EmailField(default='genzconstructors@gmail.com', max_length=254)),
                ('website', models.CharField(default='genzconstructors.co.ke', max_length=100)),
                ('whatsapp_number', models.CharField(default='254713706103', help_text='Phone number format for WhatsApp API without + or spaces (e.g. 254713706103)', max_length=50)),
                ('address', models.CharField(blank=True, help_text='Only enter verified physical operating location', max_length=255)),
                ('business_hours', models.CharField(blank=True, default='Mon - Fri: 8:00 AM - 5:00 PM | Sat: 8:00 AM - 1:00 PM', max_length=150)),
                ('facebook_url', models.URLField(blank=True, help_text='Official Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Official Instagram profile URL')),
                ('logo', models.ImageField(blank=True, help_text='Official brand logo', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon icon', null=True, upload_to='branding/')),
                ('default_meta_title', models.CharField(default='Gen-Z Constructors Limited Company | Construction & Building Solutions', max_length=255)),
                ('default_meta_description', models.TextField(default='Gen-Z Constructors Limited Company delivers modern construction, architectural design, structural engineering, renovations and building solutions across Kenya. Building Your Vision, Constructing Your Future.')),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps iframe URL or embed code (optional)')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Gallery Image',
                'verbose_name_plural': 'Project Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.service'),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Project Location / County')),
                ('project_type', models.CharField(choices=[('residential_new', 'New Residential Building / House'), ('commercial_new', 'Commercial Construction'), ('architectural_design', 'Architectural & Structural Design'), ('renovation_remodel', 'Renovation & Extension'), ('repairs_maintenance', 'Building Repairs & Maintenance'), ('landscaping', 'Landscaping & Exterior Works'), ('biodigester', 'Biodigester / Waste Management'), ('other', 'Other Building Solution')], default='residential_new', max_length=50, verbose_name='Project Category')),
                ('project_size', models.CharField(blank=True, max_length=150, verbose_name='Estimated Size (e.g. 4 Bedroom House, 500 sq m)')),
                ('preferred_start_date', models.CharField(choices=[('immediately', 'Immediately (Within 2 weeks)'), ('1_month', 'Within 1 Month'), ('1_3_months', '1 - 3 Months'), ('3_6_months', '3 - 6 Months'), ('planning', 'Currently in Planning Stage')], default='1_month', max_length=50, verbose_name='Preferred Start Timeline')),
                ('budget', models.CharField(choices=[('under_500k', 'Under KES 500,000'), ('500k_1m', 'KES 500,000 - 1,000,000'), ('1m_3m', 'KES 1,000,000 - 3,000,000'), ('3m_5m', 'KES 3,000,000 - 5,000,000'), ('5m_10m', 'KES 5,000,000 - 10,000,000'), ('above_10m', 'Above KES 10,000,000'), ('undecided', 'To Be Determined / Need Consultation')], default='undecided', max_length=50, verbose_name='Budget Estimate')),
                ('description', models.TextField(verbose_name='Project Details & Scope')),
                ('referral_source', models.CharField(blank=True, max_length=100, verbose_name='How did you hear about us?')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=core.models.safe_attachment_path, validators=[core.models.validate_file_extension], verbose_name='Project Document / Plan (PDF, JPG, PNG under 10MB)')),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('in_progress', 'In Discussion / Progress'), ('completed', 'Completed / Won'), ('closed', 'Closed / Archived')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for company managers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.service', verbose_name='Specific Service (Optional)')),
            ],
            options={
                'verbose_name': 'Project Enquiry / Quote Request',
                'verbose_name_plural': 'Project Enquiries & Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('role_or_company', models.CharField(blank=True, help_text='e.g. Homeowner, Nyali or Commercial Client', max_length=150)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('featured', models.BooleanField(default=True)),
                ('is_placeholder', models.BooleanField(default=False, help_text='Indicates editable placeholder awaiting real client review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.project')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
