# Generated by Django 6.1 on 2026-09-04 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_x_url_sitesettings_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Or direct image URL (e.g. https://... - alternative to file upload)', max_length=500),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or direct image URL (e.g. https://...)', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Or direct image URL (e.g. https://... - alternative to file upload)', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload image file from device', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file', null=True, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload image file from device', null=True, upload_to='services/'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload image file', null=True, upload_to='services/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Or direct image URL (e.g. https://...)', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Gallery Image',
                'verbose_name_plural': 'Service Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
